services:
   postgres:
      image: postgres:18-alpine
      ports:
         - "5432:5432"
      environment:
         POSTGRES_USER: loaner
         POSTGRES_PASSWORD: loaner
         POSTGRES_DB: loaner
      volumes:
        - pgdata:/var/lib/postgresql/data
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U loaner"]
         interval: 5s
         timeout: 5s
         retries: 5

   migrate:
      image: migrate/migrate
      depends_on:
         postgres:
            condition: service_healthy
      volumes:
         - ./migrations:/migrations
      command: ["-path", "/migrations", "-database", "postgres://loaner:loaner@postgres:5432/loaner?sslmode=disable", "up"]

   server:
      build: .
      depends_on:
         migrate:
            condition: service_completed_successfully
      environment:
         DATABASE_URL: postgres://loaner:loaner@postgres:5432/loaner?sslmode=disable
         HTTP_PORT: "8080"
         GRPC_PORT: "9090"
      ports:
         - "8080:8080"
         - "9090:9090"

volumes:
   pgdata:
